@extends('layouts.app')
@section('title',$invoice->exists?'Edit Vehicle Invoice':'New Vehicle Invoice')
@section('page_title',$invoice->exists?'Edit Vehicle Invoice':'New Vehicle Invoice')
@section('content')
<style>
.vi-card{background:var(--bs-body-bg);border:1px solid var(--bs-border-color);border-radius:8px;box-shadow:var(--bs-box-shadow-sm);overflow:hidden;margin-bottom:16px}.vi-head{padding:16px 20px;border-bottom:1px solid var(--bs-border-color);font-weight:800}.vi-body{padding:20px}.pay-row{display:grid;grid-template-columns:150px 160px 160px 1fr 44px;gap:10px;margin-bottom:10px}.totals{max-width:380px;margin-left:auto}.totals div{display:flex;justify-content:space-between;border-bottom:1px dashed var(--bs-border-color);padding:8px 0}.totals .grand{font-size:18px;font-weight:900}@media(max-width:800px){.pay-row{grid-template-columns:1fr}.totals{max-width:none}}
</style>
<form method="POST" action="{{ $invoice->exists ? route('company.vehicle-invoices.update',$invoice) : route('company.vehicle-invoices.store') }}">
@csrf @if($invoice->exists)@method('PUT')@endif
<div class="vi-card"><div class="vi-head">Customer, Vehicle & Sale</div><div class="vi-body"><div class="form-grid">
<div><label>Customer *</label><select class="form-select" name="customer_id" required><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id',$invoice->customer_id)==$customer->id)>{{ $customer->name }} {{ $customer->phone ? ' - '.$customer->phone : '' }}</option>@endforeach</select></div>
<div><label>Vehicle *</label><select class="form-select" id="vehicle_id" name="vehicle_id" required><option value="">Select vehicle</option>@foreach($vehicles as $vehicle)<option value="{{ $vehicle->id }}" data-price="{{ $vehicle->sale_price }}" data-category="{{ $vehicle->vehicle_category_id }}" @selected(old('vehicle_id',$invoice->vehicle_id)==$vehicle->id)>{{ $vehicle->make_model }} {{ $vehicle->registration_no ? ' - '.$vehicle->registration_no : '' }}</option>@endforeach</select></div>
<div><label>Vehicle Category *</label><select class="form-select" id="vehicle_category_id" name="vehicle_category_id" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" data-warranty="{{ $category->default_warranty_provider_id }}" data-months="{{ $category->default_warranty_months }}" @selected(old('vehicle_category_id',$invoice->vehicle_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>
<div><label>Invoice Date *</label><input class="form-control" type="date" name="invoice_date" value="{{ old('invoice_date',$invoice->invoice_date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" required></div>
<div><label>Sale Date</label><input class="form-control" type="date" name="sale_date" value="{{ old('sale_date',$invoice->sale_date?->format('Y-m-d') ?? now()->format('Y-m-d')) }}"></div>
<div><label>Transaction Type</label><select class="form-select" name="transaction_type">@foreach(['vehicle_sale'=>'Vehicle Sale','vehicle_reservation'=>'Vehicle Reservation / Deposit','part_payment'=>'Part Payment','final_payment'=>'Final Payment'] as $v=>$l)<option value="{{ $v }}" @selected(old('transaction_type',$invoice->transaction_type)===$v)>{{ $l }}</option>@endforeach</select></div>
<div><label>Vehicle Price *</label><input class="form-control calc" id="vehicle_price" type="number" step="0.01" name="vehicle_price" value="{{ old('vehicle_price',$invoice->vehicle_price) }}" required></div>
<div><label>Discount</label><input class="form-control calc" id="discount" type="number" step="0.01" name="discount" value="{{ old('discount',$invoice->discount ?? 0) }}"></div>
<div><label>Total Sale Price</label><input class="form-control" id="total_sale_price" readonly></div>
</div></div></div>

<div class="vi-card"><div class="vi-head">Warranty</div><div class="vi-body"><div class="form-grid">
<div><label>Warranty Provider</label><select class="form-select" id="warranty_provider_id" name="warranty_provider_id"><option value="">No Warranty</option>@foreach($warrantyProviders as $provider)<option value="{{ $provider->id }}" @selected(old('warranty_provider_id',$invoice->warranty_provider_id)==$provider->id)>{{ $provider->name }}</option>@endforeach</select></div>
<div><label>Warranty Duration</label><select class="form-select" id="warranty_duration_months" name="warranty_duration_months"><option value="">Select months</option>@foreach($warrantyDurations as $duration)<option value="{{ $duration->months }}" @selected((string)old('warranty_duration_months',$invoice->warranty_duration_months)===(string)$duration->months)>{{ $duration->name }}</option>@endforeach</select></div>
</div></div></div>

<div class="vi-card"><div class="vi-head d-flex justify-content-between align-items-center"><span>Payments</span><button class="btn btn-sm btn-primary" type="button" id="addPayment"><i class="ti ti-plus"></i> Add Payment</button></div><div class="vi-body" id="payments">
@php $oldPayments=old('payments',$invoice->exists?$invoice->payments->map(fn($p)=>['payment_date'=>$p->payment_date?->format('Y-m-d'),'payment_type'=>$p->payment_type,'method'=>$p->method,'amount'=>$p->amount,'notes'=>$p->notes])->toArray():[['payment_date'=>now()->format('Y-m-d'),'payment_type'=>'deposit','method'=>'Bank Transfer','amount'=>'','notes'=>'']]); @endphp
@foreach($oldPayments as $i=>$p)<div class="pay-row"><input class="form-control" type="date" name="payments[{{ $i }}][payment_date]" value="{{ $p['payment_date'] ?? now()->format('Y-m-d') }}"><select class="form-select" name="payments[{{ $i }}][payment_type]">@foreach(['deposit'=>'Deposit','part_payment'=>'Part Payment','further_payment'=>'Further Payment','final_payment'=>'Final Payment'] as $v=>$l)<option value="{{ $v }}" @selected(($p['payment_type']??'deposit')===$v)>{{ $l }}</option>@endforeach</select><select class="form-select" name="payments[{{ $i }}][method]">@foreach($paymentMethods as $method)<option value="{{ $method->name }}" @selected(($p['method']??'')===$method->name)>{{ $method->name }}</option>@endforeach<option value="Cash" @selected(($p['method']??'')==='Cash')>Cash</option><option value="Bank Transfer" @selected(($p['method']??'')==='Bank Transfer')>Bank Transfer</option><option value="Card" @selected(($p['method']??'')==='Card')>Card</option><option value="Other" @selected(($p['method']??'')==='Other')>Other</option></select><input class="form-control payment-amount" type="number" step="0.01" name="payments[{{ $i }}][amount]" value="{{ $p['amount'] ?? '' }}" placeholder="Amount"><button class="btn btn-light text-danger remove-payment" type="button"><i class="ti ti-trash"></i></button><input type="hidden" name="payments[{{ $i }}][notes]" value="{{ $p['notes'] ?? '' }}"></div>@endforeach
<div class="totals"><div><span>Total Paid</span><strong id="paidTotal">0.00</strong></div><div><span>Balance</span><strong id="balanceTotal">0.00</strong></div><div class="grand"><span>Status</span><strong id="paymentStatus">Outstanding</strong></div></div>
</div></div>
<div class="vi-card"><div class="vi-head">Notes</div><div class="vi-body"><textarea class="form-control" name="notes" rows="3">{{ old('notes',$invoice->notes) }}</textarea></div></div>
<div class="form-actions"><button class="btn btn-primary px-4">Generate Invoice</button><a class="btn btn-light" href="{{ route('company.vehicle-invoices.index') }}">Cancel</a></div>
</form>
<script>
(function(){var payments=document.getElementById('payments'), price=document.getElementById('vehicle_price'), discount=document.getElementById('discount'), total=document.getElementById('total_sale_price');function n(v){return parseFloat(v)||0}function f(v){return (Math.round(v*100)/100).toFixed(2)}function calc(){var due=Math.max(0,n(price.value)-n(discount.value));total.value=f(due);var paid=0;payments.querySelectorAll('.payment-amount').forEach(i=>paid+=n(i.value));document.getElementById('paidTotal').textContent=f(paid);document.getElementById('balanceTotal').textContent=f(Math.max(0,due-paid));document.getElementById('paymentStatus').textContent=paid>=due&&due>0?'Paid':(paid>0?'Part Paid':'Outstanding')}document.addEventListener('input',e=>{if(e.target.matches('.calc,.payment-amount'))calc()});document.getElementById('vehicle_id').addEventListener('change',function(){var o=this.selectedOptions[0]; if(o){ if(!price.value || price.value==='0.00') price.value=o.dataset.price||''; var cat=o.dataset.category; if(cat) document.getElementById('vehicle_category_id').value=cat; } calc();});document.getElementById('vehicle_category_id').addEventListener('change',function(){var o=this.selectedOptions[0]; if(o){ if(o.dataset.warranty) document.getElementById('warranty_provider_id').value=o.dataset.warranty; if(o.dataset.months) document.getElementById('warranty_duration_months').value=o.dataset.months; }});document.getElementById('addPayment').addEventListener('click',function(){var row=payments.querySelector('.pay-row').cloneNode(true);row.querySelectorAll('input').forEach(i=>{if(i.type==='date') i.value=new Date().toISOString().slice(0,10); else i.value=''});payments.insertBefore(row,payments.querySelector('.totals'));reindex();calc();});payments.addEventListener('click',e=>{var b=e.target.closest('.remove-payment'); if(!b)return; if(payments.querySelectorAll('.pay-row').length>1)b.closest('.pay-row').remove(); reindex(); calc();});function reindex(){payments.querySelectorAll('.pay-row').forEach((r,i)=>r.querySelectorAll('input,select').forEach(el=>el.name=el.name.replace(/payments\[\d+\]/,'payments['+i+']')))}calc();})();
</script>
@endsection
