<?php
namespace App\Http\Controllers;

use App\Models\Branch;
use App\Models\Customer;
use App\Models\PaymentMethod;
use App\Models\Vehicle;
use App\Models\VehicleCategory;
use App\Models\VehicleSaleInvoice;
use App\Models\WarrantyProvider;
use App\Models\WarrantyDuration;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class CompanyVehicleSaleInvoiceController extends Controller
{
    private const GENERAL_TERMS = "TERMS & CONDITIONS\nThe buyer confirms they have had the opportunity to test drive and inspect the vehicle, ask questions, and confirm they are satisfied with the vehicle condition. The buyer confirms the vehicle details, price and agreed terms have been checked before completing the purchase. Any outstanding balance must be paid in full in accordance with the agreed payment arrangements. Warranty terms, where applicable, are subject to the selected warranty provider.";
    public function index(){ return view('company.vehicle_invoices.index',['invoices'=>VehicleSaleInvoice::with('customer','vehicle')->where('branch_id',$this->companyId())->latest()->paginate(15)]); }
    public function create(){ return view('company.vehicle_invoices.form',$this->formData(new VehicleSaleInvoice(['invoice_date'=>now(),'sale_date'=>now(),'transaction_type'=>'vehicle_sale']))); }
    public function store(Request $request){ $invoice=DB::transaction(fn()=> $this->save($request,$this->validated($request))); return redirect()->route('company.vehicle-invoices.show',$invoice)->with('success','Vehicle invoice created.'); }
    public function show(VehicleSaleInvoice $vehicle_invoice){ $this->authorizeInvoice($vehicle_invoice); $vehicle_invoice->load('customer','vehicle.category','category','warrantyProvider','payments'); return view('company.vehicle_invoices.show',['invoice'=>$vehicle_invoice]); }
    public function edit(VehicleSaleInvoice $vehicle_invoice){ $this->authorizeInvoice($vehicle_invoice); $vehicle_invoice->load('payments'); return view('company.vehicle_invoices.form',$this->formData($vehicle_invoice)); }
    public function update(Request $request, VehicleSaleInvoice $vehicle_invoice){ $this->authorizeInvoice($vehicle_invoice); DB::transaction(fn()=> $this->save($request,$this->validated($request),$vehicle_invoice)); return redirect()->route('company.vehicle-invoices.show',$vehicle_invoice)->with('success','Vehicle invoice updated.'); }
    private function formData(VehicleSaleInvoice $invoice): array { $this->ensureWarrantyDurationDefaults(); return ['invoice'=>$invoice,'customers'=>Customer::where('branch_id',$this->companyId())->orderBy('name')->get(),'vehicles'=>Vehicle::with('category')->where('branch_id',$this->companyId())->orderBy('make_model')->get(),'categories'=>VehicleCategory::where('branch_id',$this->companyId())->where('is_active',true)->orderBy('name')->get(),'warrantyProviders'=>WarrantyProvider::where('branch_id',$this->companyId())->where('is_active',true)->orderBy('name')->get(),'warrantyDurations'=>WarrantyDuration::where('branch_id',$this->companyId())->where('is_active',true)->orderBy('months')->get(),'paymentMethods'=>PaymentMethod::where(fn($q)=>$q->where('branch_id',$this->companyId())->orWhereNull('branch_id'))->where('is_active',true)->orderBy('name')->get()]; }
    private function validated(Request $request): array { return $request->validate(['customer_id'=>['required',Rule::in(Customer::where('branch_id',$this->companyId())->pluck('id')->all())],'vehicle_id'=>['required',Rule::in(Vehicle::where('branch_id',$this->companyId())->pluck('id')->all())],'vehicle_category_id'=>['required',Rule::in(VehicleCategory::where('branch_id',$this->companyId())->pluck('id')->all())],'invoice_date'=>['required','date'],'sale_date'=>['nullable','date'],'transaction_type'=>['required',Rule::in(['vehicle_sale','vehicle_reservation','part_payment','final_payment'])],'vehicle_price'=>['required','numeric','min:0'],'discount'=>['nullable','numeric','min:0'],'warranty_provider_id'=>['nullable',Rule::in(WarrantyProvider::where('branch_id',$this->companyId())->pluck('id')->all())],'warranty_duration_months'=>['nullable','integer','min:0','max:120'],'notes'=>['nullable','max:2000'],'payments'=>['nullable','array'],'payments.*.payment_date'=>['required_with:payments','date'],'payments.*.payment_type'=>['required_with:payments',Rule::in(['deposit','part_payment','final_payment','further_payment'])],'payments.*.method'=>['required_with:payments','max:60'],'payments.*.amount'=>['required_with:payments','numeric','min:0.01'],'payments.*.notes'=>['nullable','max:500']]); }
    private function save(Request $request, array $data, ?VehicleSaleInvoice $invoice=null): VehicleSaleInvoice { $category=VehicleCategory::find($data['vehicle_category_id']); $provider=filled($data['warranty_provider_id']??null)?WarrantyProvider::find($data['warranty_provider_id']):null; $discount=(float)($data['discount']??0); $total=max(0,(float)$data['vehicle_price']-$discount); $paid=collect($data['payments']??[])->sum(fn($p)=>(float)$p['amount']); $balance=max(0,$total-$paid); if(!$invoice){ $branch=Branch::findOrFail($this->companyId()); $seq=VehicleSaleInvoice::withTrashed()->where('branch_id',$branch->id)->count()+1; $invoice=new VehicleSaleInvoice(['invoice_no'=>sprintf('%s-SALE-%06d',$branch->invoice_prefix?:$branch->code,$seq),'branch_id'=>$branch->id,'created_by'=>auth()->id()]); } $invoice->fill(['customer_id'=>$data['customer_id'],'vehicle_id'=>$data['vehicle_id'],'vehicle_category_id'=>$category?->id,'invoice_date'=>$data['invoice_date'],'sale_date'=>$data['sale_date']??null,'transaction_type'=>$data['transaction_type'],'vehicle_price'=>$data['vehicle_price'],'discount'=>$discount,'total_sale_price'=>$total,'total_paid'=>$paid,'balance_amount'=>$balance,'payment_status'=>$balance<=0?'paid':($paid>0?($data['transaction_type']==='vehicle_reservation'?'deposit':'part_paid'):'outstanding'),'warranty_provider_id'=>$provider?->id,'warranty_provider_name'=>$provider?->name,'warranty_duration_months'=>$data['warranty_duration_months']??$category?->default_warranty_months,'warranty_terms'=>$provider?->terms,'vehicle_terms'=>$category?->terms,'general_terms'=>self::GENERAL_TERMS,'notes'=>$data['notes']??null]); $invoice->save(); $invoice->payments()->delete(); foreach($data['payments']??[] as $payment){ $invoice->payments()->create($payment); } Vehicle::whereKey($data['vehicle_id'])->update(['status'=>$balance<=0?'sold':'reserved','vehicle_category_id'=>$category?->id,'sale_price'=>$data['vehicle_price']]); return $invoice; }
    private function companyId(): int { abort_unless(auth()->user()->branch_id,403); return auth()->user()->branch_id; }
    private function authorizeInvoice(VehicleSaleInvoice $invoice): void { abort_unless($invoice->branch_id===$this->companyId(),403); }
    private function ensureWarrantyDurationDefaults(): void { foreach ([0,3,6,12,18,24,36,48,60] as $months) { WarrantyDuration::firstOrCreate(['branch_id'=>$this->companyId(),'months'=>$months],['name'=>$months.' month'.($months===1?'':'s'),'is_system'=>true,'is_active'=>true]); } }
}
